### PR TITLE
add tests for jira component creation -> master

### LINKED ISSUE #255: JIRA components are (wrongly) created for auxiliary repositories
**Describe the bug**
Today components are created even for auxiliary system repositories which is wrong

**To Reproduce**
Create a  new ODS project thru the provision app - and then check jira - 2 components were created. `Technology_` (design and ocp-config)

**Expected behavior**
Components only created for quickstarters

**Affected version (please complete the following information):**
 - OpenDevStack [1.1 / 1.2x]

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```

2019-10-17 02:34:05 DEBUG o.o.p.c.ProjectApiController - Nothing to do on project PRJ
--
  | 2019-10-17 02:34:05 DEBUG o.o.provision.services.JiraAdapter - Repo prj-occonfig-artifacts .../projects/PRJ/repos/prj-occonfig-artifacts/browse  for project PRJ
  | 2019-10-17 02:34:05 DEBUG o.o.p.util.rest.RestClientCall - Prepare request for execution
  | 2019-10-17 02:34:05 DEBUG o.o.p.util.rest.RestClientCall - Converted rest object: {
  | "name" : "Technology-occonfig-artifacts",
  | "description" : "Technology component prj-occonfig-artifacts stored at .../projects/PRJ/repos/prj-occonfig-artifacts/browse ",
  | "project" : "PRJ"
  | }
  | 2019-10-17 02:34:05 DEBUG o.o.p.util.rest.RestClientCall - Prepared URL [.../rest/api/latest/component ]
  | 2019-10-17 02:34:05 DEBUG o.o.p.util.rest.RestClientCall - Prepared request: [Request{method=POST, url=.../rest/api/latest/component , tag=null}]
  | 2019-10-17 02:34:06 DEBUG o.o.provision.util.rest.RestClient - URL: .../rest/api/latest/component , method: POST, response-code: 201, responce-body: <body was omitted. Please enable tracing on class in order to see response body>
  | 2019-10-17 02:34:06 DEBUG o.o.provision.services.JiraAdapter - Repo prj-design .../projects/PRJ/repos/prj-design/browse  for project PRJ
  | 2019-10-17 02:34:06 DEBUG o.o.p.util.rest.RestClientCall - Prepare request for execution
  | 2019-10-17 02:34:06 DEBUG o.o.p.util.rest.RestClientCall - Converted rest object: {
  | "name" : "Technology-design",
  | "description" : "Technology component prj-design stored at .../projects/PRJ/repos/prj-design/browse ",
  | "project" : "PRJ"
  | }
  | 2019-10-17 02:34:06 DEBUG o.o.p.util.rest.RestClientCall - Prepared URL .../rest/api/latest/component ]
  | 2019-10-17 02:34:06 DEBUG o.o.p.util.rest.RestClientCall - Prepared request: [Request{method=POST, url=.../rest/api/latest/component , tag=null}]
  | 2019-10-17 02:34:06 DEBUG o.o.provision.util.rest.RestClient - URL: .../rest/api/latest/component , method: POST, response-code: 201, responce-body: <body was omitted. Please enable tracing on class in order to see response body>


```

### PR DESCRIPTION
**Pull request by clemensutschig**
fixes #255

### CODE REVIEW

**Comment by clemensutschig** [comment]
@stefanlack  - I have a really big issue here .. I ran spotlessApply .. and locally spotlessCheck works (and then pushed) .. but in the travis build this fails ...thoughts?

**Comment by rattermeyer** [comment]
What has changed are line endings. Line endings are again in with CRLF:

file src/test/java/org/opendevstack/provision/util/rest/RestClientTest.java
src/test/java/org/opendevstack/provision/util/rest/RestClientTest.java: ASCII text, with CRLF line terminators

question is / option:
* ignore line endings
* get the git clients correctly [configured](https://help.github.com/en/articles/configuring-git-to-handle-line-endings)

This might also be the issue on the other PR #254 (need to check)

**Comment by clemensutschig** [comment]
@rattermeyer what do I need to configure now, this is super frustrating ...

**Comment by rattermeyer** [comment]
Indeed, I find this line ending thing also frustrating.
your last commit 8613ed (legacy api test) changed the line endings:
git show 8613ed

So my recommendation would be:
add the global options

git config --global core.autocrlf true

reclone the project and reapply your changes.
If you now commit, you should only see your files changed in the commit.

I would also suggest to add an .gitattributes to the project (as we already did with most of the other ones) to control the CRLF behavior, see: 
https://github.com/opendevstack/ods-project-quickstarters/blob/master/.gitattributes
(I will do this in a seperate ticket)

**Comment by rattermeyer** [comment]
added the gitattributes in #258

**Comment by rattermeyer** [comment]
superseded by #260

**Pull request closed without merging**
