### PR TITLE
Bug/oc project admin & description length - fix for 1.0x

### LINKED ISSUE #71: Openshift projects are created with current user as admin, even in case of special permission set
Today we pass down the current (logged in) principal to rundeck and subsequently to openshift (as project role admin) example below

tech_integration          admin   -> the currently logged in user 

rather than taking the provided project admin (in case of special permission set = true)

https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/java/org/opendevstack/provision/services/RundeckAdapter.java#L185

### PR DESCRIPTION
**Pull request by clemensutschig**
fixes #71 against 1.0x
fixes #70 against 1.0x

### CODE REVIEW

**Comment by clemensutschig** [comment]
@michaelsauter  - i sort of understand you.. but its important enough while surgical to do imho..

**Comment by michaelsauter** [comment]
@clemensutschig I don't want to be a pain, but this change is somewhat breaking - you need to rebuild the base slave image, and the maven slave image for it to work. I would want to avoid this for patch releases unless it is 100% required to fix a bug. Here, we are dealing with a feature. 

Since you already have this on prem in the `production` branch, I don't see a benefit to put this into `1.0.x` either ...

**Comment by clemensutschig** [comment]
@michaelsauter- you are.. but thats ok. Decline the sqjar One. And that one i fix. Yak

**Comment by michaelsauter** [comment]
@clemensutschig I rewrote the branch - do the changes look good to you now?

**Pull request merged**
