### PR TITLE
Updated component id reg exp to ignore tests word

### PR DESCRIPTION
**Pull request by felipecruz91**
Refers to #620

### CODE REVIEW

**Review by stitakis — CHANGES_REQUESTED** [review]
Thanks for contributing! I believe there is unit test https://github.com/opendevstack/ods-provisioning-app/blob/master/src/test/java/org/opendevstack/provision/model/OpenProjectDataValidatorTest.java needs to be modified too. Can you please update the unit test?
btw... what happens if name the component "dev"... asking because I read the bug issue but it was not clear for me why the jenkins pipeline failed if the component is named "tests"

**Review by stitakis — APPROVED** [review]
well done! Thanks!

**Comment by felipecruz91** [comment]
@stitakis Build is failing because of some formatting rules, @stitakis could you have a look at that, please?

**Comment by stitakis** [comment]
@felipecruz91 I took a look, you need to run `./gradlew spotlessApply` to fix the formatting, then commit the changed files and push again.

**Comment by felipecruz91** [comment]
@stitakis It doesn't seem to work on the enterprise laptop (I've already configured the HTTP_PROXY env vars)

image

**Review by stitakis — APPROVED** [review]

**Pull request merged**
