### PR TITLE
add gateway kong quickstarter configuration

### PR DESCRIPTION
**Pull request by stefanlack**
Adds configuration for new quickstarter. See https://github.com/opendevstack/ods-quickstarters/pull/291

### CODE REVIEW

**Comment by stitakis** [comment]
Hi @stefanlack we are in the process of separating the quickstarters configuration from the application.properites in issue #363. In this context, do you think we need to add kong to the default list of quickstarters or would you prefer to keep it as part of your own deployment configuration on your side? @michaelsauter, your thoughts?

**Comment by stefanlack** [comment]
Since we are still on the 2.x version, the change in issue #363 has no effect for us. Since Kong Quickstart is still not migrated to 3.x version, feel free to not add the quickstarter to the default list.

If the migration is done and the kong quickstarter is available for 3.x version, we can add it later to the default configuration.

**Comment by stitakis** [comment]
@stefanlack who will be the active mantainer of kong qs? Asking because we are aiming to add to the default configuration and keep in `ods-quickstarters` only the quickstarters with active maintainers

**Comment by stefanlack** [comment]
As written in https://github.com/opendevstack/ods-quickstarters/pull/291#issuecomment-635272931, the opendevstack team at opitz-consulting is not going to migrate to 3. in the near future. Therefore, we are not able to maintain the quickstarter, I am sorry to say.

**Pull request closed without merging**
