### PR TITLE
Project specific cd user(2)

### PR DESCRIPTION
**Pull request by stefanlack**
replacement of https://github.com/opendevstack/ods-provisioning-app/pull/285

### CODE REVIEW

**Comment by stefanlack** [comment]
question from @michaelsauter 

> @stefanlack Can you please share how this affects the API? I think there must be a way to pass the technical user name into it but I fail to see where this happens here. Do you know?

**Comment by clemensutschig** [comment]
@michaelsauter 
https://github.com/opendevstack/ods-provisioning-app/pull/297/files#diff-e5f86a2b504a63d2dc9c58738c919faeR46 

it's just one new field in the openprojectdata pojo which is the API :D

**Comment by michaelsauter** [comment]
@clemensutschig Got it, thanks!

**Comment by clemensutschig** [comment]
@stefanlack  - this is a crucial one for ODS 2 ..

org.opendevstack.provision.controller.E2EProjectAPIControllerTest > testQuickstarterProvisionOnNewOpenProjectInclDeleteWholeProject FAILED
    java.io.IOException at E2EProjectAPIControllerTest.java:507
org.opendevstack.provision.controller.E2EProjectAPIControllerTest > testQuickstarterProvisionOnNewOpenProjectFail FAILED
    org.mockito.exceptions.verification.junit.ArgumentsAreDifferent at E2EProjectAPIControllerTest.java:633

**Pull request merged**
