### PR TITLE
ds-dash quickstarter

### PR DESCRIPTION
**Pull request by gerardcl**
relates to https://github.com/opendevstack/ods-quickstarters/issues/77

### CODE REVIEW

**Comment by clemensutschig** [comment]
@gerardcl  - can you please merge this into master?

**Comment by michaelsauter** [comment]
No, this should be closed. Dash is not a quickstarter in the official repo - please see my comment. 

Let's see actual usage, and until we know for sure that we want to support and maintain this under the open source umbrella, we should not pick it up. **We need fewer, not more quickstarters as part of the official distribution**.

**Comment by gerardcl** [comment]
AFAIK it is already being used by many different DS colleagues, @sklingel correcte me if I am wrong, but they can anyway use it from jupyter QS skeleton or internal QS too. I am fine on closing it.

**Comment by michaelsauter** [comment]
Let's close this for now as the other repo does not contain the quickstarter. 

Next step is to develop a nice way to configure quickstarters (that will be done for v3) and then we decide which quickstarter goes into which repo for v3 :)

**Pull request closed without merging**
