### PR TITLE
adds trust all certificates and odsbox spring profile

### LINKED ISSUE #579: add support for odsbox for local development
As developer I would like to be able to configure the Provisioning App with an ODSBox over openvpn.
Being able to connect from local development environment to ODSBox will improve productivity of developer.

Proposed solution to support ODSBox:
- add flag to trust all certificates in `RESTClient.java`: this flag should default to `false` and only be set to `true` when running provisioning app locally. This will be necessary to avoid a repetive task of importing the ODSBox https certificate in the truststore everytime a new ODSBox is used.
- provide a `odsbox` spring profile with all preconfigured urls to allow developer to quickly connect to the ODSBox

### PR DESCRIPTION
**Pull request by stitakis**
fixes #579

### CODE REVIEW

**Comment by stitakis** [comment]
@georgfedermann fyi

**Comment by michaelsauter** [comment]
For later - can you ensure to update the docs with this?

**Comment by stitakis** [comment]
@michaelsauter yes, will do... btw. I quickly took a look the ods-core docs because I'd like to reference odsbox in the prov app documentation. I didn't find anything. Am I correct? odsbox docs are missing in ods-core?

**Comment by georgfedermann** [comment]
@stitakis thanks for the reminder, I'll have to add the docs

**Review by georgfedermann — APPROVED** [review]

**Pull request merged**
