### PR TITLE
Feature/improve ods-provisioning-app docu

### PR DESCRIPTION
**Pull request by stefanlack**
See https://github.com/opendevstack/ods-provisioning-app/issues/245

### CODE REVIEW

**Comment by stefanlack** [comment]
Note: same changes are also done in ods-quickstarters. See https://github.com/opendevstack/ods-project-quickstarters/pull/374

**Comment by rattermeyer** [comment]
Short notice (also to self): we cannot prevent the docs directory from being committed. would be great to have local git to honor gitignore and travis to ignore gitignore

**Comment by stefanlack** [comment]
@rattermeyer see my solution to this  problem at https://github.com/opendevstack/ods-documentation/issues/13

**Comment by clemensutschig** [comment]
@stefanlack you overwrote my changes - eg the new api. Please fix immediatley!!!

**Comment by stefanlack** [comment]
@clemensutschig can you please specifiy, which information was overrridden.

My change has moved information from README.md to different files below [docs/modules/ROOT
](https://github.com/opendevstack/ods-provisioning-app/tree/master/docs/modules/ROOT)

image

**Pull request merged**
