### PR TITLE
feature/gh 572 improve authorization of quickstarter endpoint

### LINKED ISSUE #572: improve authorization of quickstarter endpoint

### PR DESCRIPTION
**Pull request by stitakis**
fixes #572

### CODE REVIEW

**Comment by michaelsauter** [comment]
@stitakis Can you explain this change? Why is it needed? What does it do? How? And what are the consequences?

**Comment by clemensutschig** [comment]
Is this a backport? This seems a rather big Change.

**Comment by stitakis** [comment]
@clemensutschig it is a security fix, a small change. It adds some refactoring in test classes. I'll port this to master once this PR is approved.

**Comment by stitakis** [comment]
@michaelsauter can you please have a quick look at this security fix?

**Review by michaelsauter — APPROVED** [review]
@stitakis Actual change looks small to me, and tests show the intended change, so fine with me.

**Pull request merged**
