### PR TITLE
adds getters and setters to access class member variables

### LINKED ISSUE #638: Reduce technical debt
There are some code aspects of the provisioning app that we need to improve. Goals of this issue are to clean up some antipatterns, improve unit tests, improve code readability, update dependencies, etc.

This is a preliminary list for ODS Prov App 4.x:
- All spring test should only use spring support and not a mix of spring and mockito (no @InjectMocks, etc)
- Fix encapsulation of all classes, no protected properties -> getter and setters
- Remove critical circular dependencies 
- Update Dependencies (snyk findings) und spring boot
- Fix Sonarqube findings (ev. sonarqube in .github action enable)
- Update to latest gradle v6.7.1 and remove deprecated gradle features
- Remove @author
- Remove deprecated classes like ProjectData
- etc...

### PR DESCRIPTION
**Pull request by stitakis**
partially fixes #638

### CODE REVIEW

**Comment by stitakis** [comment]
@renedupont fyi... I have disabled for this PR the finding of CodeQL, because a fix for this will be better to introduced in another branch, otherwise this PR will be even bigger. To tackle the CodeQL finding I have created this issue #667 which is high prio.

**Comment by renedupont** [comment]
ok! why is it happening now and not before though?

**Review by renedupont — APPROVED** [review]

**Comment by stitakis** [comment]
my assumption, the tool was improved.

**Comment by renedupont** [comment]
but we set a specific version (v1) of that code ql analysis in the github workflow?

**Comment by renedupont** [comment]
ok maybe this can still get new rules without updating the actual analysis software

**Pull request merged**
