### PR TITLE
Feature/add legacy api test

### PR DESCRIPTION
**Pull request by clemensutschig**
test coverage -> old content, vs new plugin

### CODE REVIEW

**Comment by clemensutschig** [comment]
@rattermeyer 

 Violations also present in 93 other files.
  Run 'gradlew spotlessApply' to fix these violations.

this is what I did and committed the changes - locally this works super fine now .. but not on travis?!

**Comment by stefanlack** [comment]
Strange. 
Examine build result at [travis](https://travis-ci.com/opendevstack/ods-provisioning-app/builds/132313922):

Is branch=master ok in this page:
image

**Comment by stefanlack** [comment]
I have executed the build from your branch without formatting issues.

**Comment by clemensutschig** [comment]
@stefanlack  - yup . and travis breaks? how is this possible.. ?

**Comment by stefanlack** [comment]
@clemensutschig Unfortunately I do not know why travis  is trying to build the master branch. 

Anyway, your master branch at https://github.com/BIX-Digital/ods-provisioning-app.git is pretty old. Maybe you may merge the master branch from https://github.com/opendevstack/ods-provisioning-app.git to your fork and check if this merge results in a clean build.

**Comment by rattermeyer** [comment]
This is also caused bei CRLF line endings getting in again. see #256

**Comment by clemensutschig** [comment]
@rattermeyer  - this is HUGELY frustrating, seriously now .. I am mega upset"!

**Pull request closed without merging**
