### PR TITLE
Spotless: Enforce formatting

### PR DESCRIPTION
**Pull request by rattermeyer**
Hi,
just as a discussion: What do you think about enforcing the formatting as Apache Beam does it using spotless:

https://cwiki.apache.org/confluence/display/BEAM/Spotless+pre-commit

BR,
Richard

### CODE REVIEW

**Comment by michaelsauter** [comment]
I'm fine with this - we do that for our product internally. Not using spotless, but running the google java formatter as part of the pre-commit hook.

**Comment by stefanlack** [comment]
Nice idea.
But: before merging this to master, we should consider that this plugin will change the formatting of 91 files, when the gradle build is executed the first time. It will not only reformat the changed files, but all of them.

For example:
image

@clemensutschig  and @michaelsauter if this ok for you, than we shoul add all reformated files to this pull request, approve it again and merge it to master.

We should to this as soon as possiple, IMHO.

**Comment by stefanlack** [comment]
Reformatted files have been added.

**Comment by michaelsauter** [comment]
@stefanlack Agreed, we should bring all files into the correct formatting.

**Comment by rattermeyer** [comment]
as @stefanlack  has already added the formatted files, we should be fine.
Stefan, can you then approve the PR?

**Pull request merged**
